### ISSUE TITLE
getting error in 1.21.1

### ISSUE THREAD

**Issue by NOTBOOSTER** [MaxxQc/MyDrops#2]
[10:29:46 ERROR]: Could not pass event PlayerDropItemEvent to MyDrops v1.4.0
java.lang.NoClassDefFoundError: com/alessiodp/parties/api/interfaces/PartiesAPI
        at MyDrops-1.4.0.jar/net.maxxqc.mydrops.utils.Utils.canPickup(Utils.java:399) ~[MyDrops-1.4.0.jar:?]
        at MyDrops-1.4.0.jar/net.maxxqc.mydrops.utils.Utils.handleItemDrop(Utils.java:167) ~[MyDrops-1.4.0.jar:?]
        at MyDrops-1.4.0.jar/net.maxxqc.mydrops.protection.ItemDropHandler.onDrop(ItemDropHandler.java:13) ~[MyDrops-1.4.0.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-132-b48403b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.player.Player.drop(Player.java:793) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:2577) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:2572) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:2669) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1830) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.alessiodp.parties.api.interfaces.PartiesAPI
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 31 more
[10:29:48 ERROR]: Could not pass event EntityPickupItemEvent to MyDrops v1.4.0
java.lang.NoClassDefFoundError: com/alessiodp/parties/api/interfaces/PartiesAPI
        at MyDrops-1.4.0.jar/net.maxxqc.mydrops.utils.Utils.canPickup(Utils.java:399) ~[MyDrops-1.4.0.jar:?]
        at MyDrops-1.4.0.jar/net.maxxqc.mydrops.protection.ProtectionHandler.onPickup(ProtectionHandler.java:29) ~[MyDrops-1.4.0.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-132-b48403b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.item.ItemEntity.playerTouch(ItemEntity.java:514) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.world.entity.player.Player.touch(Player.java:639) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.world.entity.player.Player.aiStep(Player.java:604) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3173) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.world.entity.player.Player.tick(Player.java:288) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:835) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:346) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.network.Connection.tick(Connection.java:638) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:248) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1821) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.alessiodp.parties.api.interfaces.PartiesAPI
        ... 23 more

**Comment by MaxxQc** [comment]
Hello, it seems like the plugin is not able to find the Parties plugin. If your server does not have Parties installed, please disable the setting in the config file for it.

If it doesn’t work, please share your config.

Thank you!
________________________________
From: BHASKAR MELKANI ***@***.***>
Sent: Thursday, November 28, 2024 5:43:00 AM
To: MaxxQc/MyDrops ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MaxxQc/MyDrops] getting error in 1.21.1 (Issue #2)


[10:29:46 ERROR]: Could not pass event PlayerDropItemEvent to MyDrops v1.4.0
java.lang.NoClassDefFoundError: com/alessiodp/parties/api/interfaces/PartiesAPI
at MyDrops-1.4.0.jar/net.maxxqc.mydrops.utils.Utils.canPickup(Utils.java:399) ~[MyDrops-1.4.0.jar:?]
at MyDrops-1.4.0.jar/net.maxxqc.mydrops.utils.Utils.handleItemDrop(Utils.java:167) ~[MyDrops-1.4.0.jar:?]
at MyDrops-1.4.0.jar/net.maxxqc.mydrops.protection.ItemDropHandler.onDrop(ItemDropHandler.java:13) ~[MyDrops-1.4.0.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-132-b48403b]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at net.minecraft.world.entity.player.Player.drop(Player.java:793) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:2577) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:2572) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:2669) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1830) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.alessiodp.parties.api.interfaces.PartiesAPI
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
... 31 more
[10:29:48 ERROR]: Could not pass event EntityPickupItemEvent to MyDrops v1.4.0
java.lang.NoClassDefFoundError: com/alessiodp/parties/api/interfaces/PartiesAPI
at MyDrops-1.4.0.jar/net.maxxqc.mydrops.utils.Utils.canPickup(Utils.java:399) ~[MyDrops-1.4.0.jar:?]
at MyDrops-1.4.0.jar/net.maxxqc.mydrops.protection.ProtectionHandler.onPickup(ProtectionHandler.java:29) ~[MyDrops-1.4.0.jar:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:44) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-132-b48403b]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at net.minecraft.world.entity.item.ItemEntity.playerTouch(ItemEntity.java:514) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.world.entity.player.Player.touch(Player.java:639) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.world.entity.player.Player.aiStep(Player.java:604) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3173) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.world.entity.player.Player.tick(Player.java:288) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:835) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:346) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.network.Connection.tick(Connection.java:638) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:248) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1821) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.alessiodp.parties.api.interfaces.PartiesAPI
... 23 more

**Comment by NOTBOOSTER** [comment]
options:
  glow: true
  invulnerable: false
  pickup-delay: 0
  protection-expiry: 0
  default-glow-color: AQUA
  per-player-glow: true
  per-player-protection: true
  hide-drops-from-others: false
  database-format: sqlite
  enable-bstats: true
  enable-auto-update-checker: true
  trash-confirm-close: true
  allow-close-confirm-with-escape: false
hooks:
  parties:
    enabled: false
    players-trust-own-party-by-default: false
  mythicmobs:
    enabled: true
database:
  host: 127.0.0.1
  user: minecraft
  password: pass
  port: '3306'
  database-name: database
  tables-prefix: mydrops_
  uri: mongodb://localhost:27017
worlds:
  is-blacklist: true
  list:
  - someworld
protection:
  item-drop:
    enable: true
    player-default: true
  block-break:
    enable: true
    player-default: true
  item-frame-drop:
    enable: true
    player-default: true
  vehicle-destroy:
    enable: true
    player-default: true
  hanging-break:
    enable: true
    player-default: true
  entity-kill:
    enable: true
    player-default: true
  player-death:
    enable: false
    player-default: false
  mythic-mobs:
    enable: false
    player-default: true
messages:
  commands:
    player-only: '&cYou must be a player to use this command.'
    unknown: '&cUnknown subcommand &4&o{subcommand}'
    no-permission: '&cYou do not have permission to execute subcommand &4&o{subcommand}'
    glow:
      set: '&eGlow color set to &o{color}'
      invalid: '&eGlow color &o&6{color}&e is not valid'
    trash:
      container-title: '&cTrash bin'
    reloaded: '&aMyDrops configuration has been reloaded successfully!'
    config:
      invalid-key: '&cInvalid config key &4&o{key}'
      invalid-value: '&cInvalid config value &4&o{value}&c for key &4&o{key}'
      pos-value: '&cValue needs to be a positive number for key &4&o{key}'
      success: '&2&o{key}&a has been changed to &2&o{value}'
      added: '&2&o{value}&a has been added to &2&o{key}'
      removed: '&4&o{value}&c has been removed from &4&o{key}'
      value: '&bValue of &3&o{key}&b is &3&o{value}'
      usage: '&cUsage: /{cmd} config [key] [value]'
      type: '&bPlease type the new value in chat | &cType cancel to exit'
      placeholders: '&bPlaceholders: &3{placeholders}'
      current-value: '&bCurrent value: &3{value}'
      input-cancelled: '&cInput has been cancelled'
      right-click: '&7Right click to decrease'
      left-click: '&7Left click to increase'
      shift-click: '&7Shift + click to increase/decrease by 5'
    invalid-item: '&cYou need to be holding a valid item in order to use this command'
    trust:
      usage: '&cUsage: /{cmd} trust <add/remove/list> [player]'
      add-remove-usage: '&cUsage: /{cmd} trust {subcmd} <player>'
      add-success: '&2{player}&a has been added to your trusted list'
      add-success-party: '&2{party}&a has been added to your trusted list'
      remove-success: '&2{player}&a has been removed from your trusted list'
      remove-success-party: '&2{party}&a has been removed from your trusted list'
      already-trusted: '&4{player}&c is already part of your trusted list'
      already-trusted-party: '&4{party}&c is already part of your trusted list'
      not-trusted: '&4{player}&c is not part of your trusted list'
      not-trusted-party: '&4{party}&c is not part of your trusted list'
      list: '&eTrusted players ({count}): &6{players}'
      self: '&cYou cannot add yourself to your trusted list'
  gui:
    confirmation:
      title: '&6Confirm?'
    config:
      title: '&aConfiguration - {key}'
    color:
      title: '&bSelect a color'
  player-not-found: '&cPlayer &4{player}&c not found'
  empty: empty
  your-party: Your party
  selected-suffix: ' (selected)'
  default: '&b&oDefault value'
  help:
    header: '&eAll commands are:'
    core: '&6/{cmd}&e - Shows this help menu'
    glowcolor: '&6/{cmd} glowcolor [color]&e - Defines a new glowing color for yourself
      or open the color selection GUI'
    protection: '&6/{cmd} protection <protection type> <true/false>&e - Toggles a
      protection rule for yourself'
    trash: '&6/{cmd} trash &e - Opens up a trash bin container'
    trust: '&6/{cmd} trust <add/addparty/remove/removeparty/list> [player] &e - Controls
      your trusted list'
    config: '&6/{cmd} config [key] [value] &e - Defines the value of a setting or
      open the config GUI'
    reload: '&6/{cmd} reload &e - Reloads the configuration from file'
items:
  confirmation:
    accept:
      ==: org.bukkit.inventory.ItemStack
      v: 3955
      type: GREEN_STAINED_GLASS_PANE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"text":"","extra":["&aAccept"]}'
    decline:
      ==: org.bukkit.inventory.ItemStack
      v: 3955
      type: RED_STAINED_GLASS_PANE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"text":"","extra":["&cDecline"]}'
  gui:
    back:
      ==: org.bukkit.inventory.ItemStack
      v: 3955
      type: BARRIER
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"text":"","extra":[{"text":"Back","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"red","bold":false}]}'
    close:
      ==: org.bukkit.inventory.ItemStack
      v: 3955
      type: BARRIER
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"text":"","extra":[{"text":"Close","obfuscated":false,"italic":false,"underlined":false,"strikethrough":false,"color":"red","bold":false}]}'
    none:
      ==: org.bukkit.inventory.ItemStack
      v: 3955
      type: WHITE_WOOL
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"text":"","extra":[{"text":"None","obfuscated":false,"italic":true,"underlined":false,"strikethrough":false,"color":"white","bold":false}]}'

**Comment by MaxxQc** [comment]
Add me on discord it should be easier: maxx_qc
________________________________

**Comment by MaxxQc** [comment]
No response, I am closing this issue, contect me on discord if you still have issues :)
